---
title: "Crime in ungary"
author: "Tamás Nagy"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(magrittr)
library(broom)
library(here)

theme_set(theme_light())

```


```{r}
crime_url <- "https://www.ksh.hu/stadat_files/iga/hu/iga0003.html"

crime_raw <- 
    read_html(crime_url) |> 
    html_table(header = FALSE) |> 
    extract2(1)

crime_raw |> 
    slice(2) |> 
    unlist() |> 
    unname()

crime_header <- read_lines(here::here("eng_header.txt"))

crime_wide <- 
    crime_raw |> 
    set_names(crime_header) |> 
    slice(-(1:2)) |> 
    mutate(across(everything(), ~str_remove(., " ") |> as.numeric()))

crime_long <- 
    crime_wide |> 
    pivot_longer(-Year)

```


```{r}

crime_long |> 
    ggplot() +
    aes(x = Year, y = value, color = name) +
    geom_line(show.legend = FALSE, linewidth = 1.1) +
    geom_smooth(method = "lm", show.legend = FALSE) +
    facet_wrap(~name, scales = "free_y") +
    scale_y_continuous(labels = scales::comma_format())
    

```


```{r}

dui <- 
    crime_long |> 
    filter(name == "drink/driving")

total <-
    crime_long |> 
    filter(name == "Total")

drug <-
    crime_long |> 
    filter(name == "drug offencesb")

```


```{r}

lm(scale(value) ~ scale(Year), data = dui) |> 
    summary()

lm(scale(value) ~ scale(Year), data = total) |> 
    summary()

lm(scale(value) ~ scale(Year), data = drug) |> 
    summary()


```

```{r}
dui_model <- 
    dui |> 
    lm(value ~ poly(Year, 3), data = _)

summary(dui_model)

tidy(dui_model, conf.int = TRUE)

augment(dui_model, 
        newdata = dui,
        interval = "confidence") |> 
    ggplot() +
    aes(x = Year, y = .fitted, ymin = .lower, ymax = .upper) +
    geom_ribbon(alpha = .5, fill = "cyan") +
    geom_line()

```

```{r}

crime_nested <-
    crime_long |> 
    group_by(name) |> 
    nest() |> 
    mutate(model = map(data, ~lm(scale(value) ~ poly(Year, 3), data = .x)),
           tidy_model = map(model, tidy, conf.int = TRUE)
           ) |> 
    ungroup()

crime_nested |> 
    filter(name == "criminal mischief") |> 
    unnest(data)

# Which categories have the stronges linear trends
crime_nested |> 
    unnest(tidy_model) |> 
    select(-data, -model) |> 
    filter(term =="poly(Year, 3)1") |> 
    arrange(estimate)

crime_nested |> 
    unnest(tidy_model) |> 
    select(-data, -model) |> 
    filter(term =="poly(Year, 3)2") |> 
    arrange(estimate)

crime_nested |> 
    unnest(tidy_model) |> 
    select(-data, -model) |> 
    filter(term =="poly(Year, 3)3") |> 
    arrange(estimate)

```


